---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: my-site/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: my-site/content/search
  label: Search
  create: all
  match: "**/*"
- type: directory
  path: my-site/content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: my-site/content/about
  label: About
  create: all
  match: "**/*"
upload_dir: my-site/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.63.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.63.2
