# default config
baseURL = "https://examplesite.org"
languageCode = "en-us"
title = "Parsa | Personal Blog Template"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 6

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# navigation
[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 3

# deult parameter
[params]
logo = "images/logo.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
description = "This is meta description"
# about author
author = "Themefisher"
author_image = "images/banner-img.png"
bio = "I’m a Freelance Interactive Art Director based in France. Focusing across branding and identity, digital and print."
# Contact info
mobile = "+90 000 333 22"
email = "exmaple@ymail.com"
address = "6 rip carl Avenue CA 90733"
# Contact Form Action
contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright &copy; 2020 a theme by [themefisher.com](themefisher.com)"

# Preloader
[params.preloader]
enable = true

# search
[params.search]
enable = true

# Instagram feed
[params.instafeed]
enable = true
user_id = "4044026246"
access_token = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"

# social site
[[params.social]]
icon = "ti-facebook"
URL = "#"

[[params.social]]
icon = "ti-twitter-alt"
URL = "#"

[[params.social]]
icon = "ti-linkedin"
URL = "#"

[[params.social]]
icon = "ti-github"
URL = "#"